version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '${PRISMA_PORT}:${PRISMA_PORT}'
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_PORT}
        databases:
          default:
            connector: ${DB_CONNECTOR}
            host: ${DB_HOST}
            port: ${DB_PORT}
            user: ${DB_USER}
            password: ${DB_PASSWORD}
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~
